template: |
  # v$RESOLVED_VERSION

  ## How to Install

  See [here](https://github.com/juho05/sheetopia#install) for installation instructions.

  ## What's New?

  ### New Features

  - TODO
  
  ### Changes
  
  - TODO

  ### Bug Fixes

  - TODO

  **Full changelog:** [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
