// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    scores,
    genres,
    instruments,
    tags,
    scoreTags,
    keyValue,
    deletedTags,
    deletedScores,
    searchTextIndex,
  ];
  late final Shape0 scores = Shape0(
    source: i0.VersionedTable(
      entityName: 'scores',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 genres = Shape1(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score, genre)'],
      columns: [_column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 instruments = Shape2(
    source: i0.VersionedTable(
      entityName: 'instruments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score, instrument)'],
      columns: [_column_11, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tags = Shape3(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_14, _column_15, _column_16, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scoreTags = Shape4(
    source: i0.VersionedTable(
      entityName: 'score_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score, tag)'],
      columns: [_column_11, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 keyValue = Shape5(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_19, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 deletedTags = Shape6(
    source: i0.VersionedTable(
      entityName: 'deleted_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(tag_id)'],
      columns: [_column_21, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 deletedScores = Shape7(
    source: i0.VersionedTable(
      entityName: 'deleted_scores',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score_id)'],
      columns: [_column_23, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index searchTextIndex = i1.Index(
    'search_text_index',
    'CREATE INDEX search_text_index ON scores (search_text)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get composer =>
      columnsByName['composer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get searchText =>
      columnsByName['search_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get metadataUpdatedAt =>
      columnsByName['metadata_updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileUpdatedAt =>
      columnsByName['file_updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get metadataUploaded =>
      columnsByName['metadata_uploaded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fileUploaded =>
      columnsByName['file_uploaded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fileDownloaded =>
      columnsByName['file_downloaded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fileType =>
      columnsByName['file_type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'composer',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'search_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'metadata_updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'metadata_uploaded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (metadata_uploaded IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_uploaded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (file_uploaded IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_downloaded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (file_downloaded IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get score =>
      columnsByName['score']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genre =>
      columnsByName['genre']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'score',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES scores(id)ON UPDATE CASCADE ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'genre',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get score =>
      columnsByName['score']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instrument =>
      columnsByName['instrument']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'instrument',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get color =>
      columnsByName['color']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploaded =>
      columnsByName['uploaded']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'uploaded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (uploaded IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get score =>
      columnsByName['score']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tag =>
      columnsByName['tag']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES tags(id)ON UPDATE CASCADE ON DELETE CASCADE',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deleted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get scoreId =>
      columnsByName['score_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'score_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    scores,
    genres,
    instruments,
    tags,
    scoreTags,
    keyValue,
    deletedTags,
    deletedScores,
    logMessage,
    searchTextIndex,
  ];
  late final Shape0 scores = Shape0(
    source: i0.VersionedTable(
      entityName: 'scores',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 genres = Shape1(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score, genre)'],
      columns: [_column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 instruments = Shape2(
    source: i0.VersionedTable(
      entityName: 'instruments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score, instrument)'],
      columns: [_column_11, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tags = Shape3(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_14, _column_15, _column_16, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scoreTags = Shape4(
    source: i0.VersionedTable(
      entityName: 'score_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score, tag)'],
      columns: [_column_11, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 keyValue = Shape5(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_19, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 deletedTags = Shape6(
    source: i0.VersionedTable(
      entityName: 'deleted_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(tag_id)'],
      columns: [_column_21, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 deletedScores = Shape7(
    source: i0.VersionedTable(
      entityName: 'deleted_scores',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(score_id)'],
      columns: [_column_23, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 logMessage = Shape8(
    source: i0.VersionedTable(
      entityName: 'log_message',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index searchTextIndex = i1.Index(
    'search_text_index',
    'CREATE INDEX search_text_index ON scores (search_text)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sessionStartTime =>
      columnsByName['session_start_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get time =>
      columnsByName['time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get level =>
      columnsByName['level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tag =>
      columnsByName['tag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get message =>
      columnsByName['message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stackTrace =>
      columnsByName['stack_trace']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exception =>
      columnsByName['exception']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_start_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'message',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stack_trace',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exception',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
